project:
  type: book
  output-dir: docs

book:
  title: "Workshop Bash 2025"
  author: "José Daniel Chavez"
  date: "18/03/2025"
  page-navigation: true
  chapters:
    - index.qmd
    - 2_requisitos.qmd
    - 3_intro.qmd
    - 4_Bash.qmd
    - 5_ServidorBetterlab.qmd
    - 6_ArchivosyformatosBioinformatica.qmd
    - 7_ScriptBash.qmd
    - 8_FuncionesBasicas_pt1.qmd
    - 8_FuncionesBasicas_pt2.qmd
    - 9_EjerciciosFinales.qmd
    - 10_Buenaspracticas.qmd
    - 11_intro_git.qmd
    - 12_Instalación.qmd
    - 13_Configuración y trabajo en Git.qmd
    - 14_Ramas en Git.qmd
    - 15_Intro_GitHub.qmd
    - 16_Manejo_de_repositorios.qmd
  # Information
  repo-url: https://github.com/danielcg91/WorkShop2025 # link de Github
  sharing: [facebook, linkedin]
  favicon: "ViernesBioinfo_logo.png" # icono de la pagina en pestana

format: 
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

